package vista;
import Clases.Navegador;
import javax.swing.table.DefaultTableModel;
public class gestionConductores extends javax.swing.JFrame {
    Navegador Nav;
    DefaultTableModel tbCond;
    public gestionConductores(Navegador n) {
        initComponents();
        Nav = n;
        tbCond = new DefaultTableModel();
        tbCond.addColumn("NOMBRE");
        tbCond.addColumn("APELLIDO");
        tbCond.addColumn("CEDULA");
        tbCond.addColumn("VEHICULO");
        tbCond.addColumn("PLACA");
        tbCond.addColumn("CELULAR");
        tbConductores.setModel(tbCond);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConductores = new javax.swing.JTable();
        btnRegV = new javax.swing.JButton();
        btnOpenReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DE CONDUCTORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        tbConductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbConductores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 850, 410));

        btnRegV.setText("ASIGNAR VIAJE");
        getContentPane().add(btnRegV, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 210, 30));

        btnOpenReg.setText("REGISTRAR CONDUCTOR");
        btnOpenReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenRegActionPerformed
        Nav.rCond.setVisible(true);
    }//GEN-LAST:event_btnOpenRegActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenReg;
    private javax.swing.JButton btnRegV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbConductores;
    // End of variables declaration//GEN-END:variables
}
